'use client'

import WalletContextProvider from '@/components/WalletContextProvider'
import './globals.css'
import { CacheProvider } from '@chakra-ui/next-js'
import { ChakraProvider } from '@chakra-ui/react'
import { extendTheme } from "@chakra-ui/react"


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const colors = {
  background: "#1F1F1F",
  accent: "#833BBE",
  bodyText: "rgba(255, 255, 255, 0.75)",
}

const theme = extendTheme({ colors })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CacheProvider>

          <ChakraProvider>
            <WalletContextProvider>
              {children}
            </WalletContextProvider>
          </ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  )
}
